# (dataset_year, dataset_name, label, tier, fact)
# tier: 1 easy, 2 medium, 3 hard

POOL = [
    ("bc1", "Roman Empire", "Roman Empire", 1, "Under Augustus, Rome ruled every shore of the Mediterranean."),
    ("bc323", "Empire of Alexander", "Empire of Alexander", 1, "Alexander died in Babylon this year, aged 32. His generals soon split the empire."),
    ("1530", "Ottoman Empire", "Ottoman Empire", 1, "It had taken Egypt in 1517 and besieged Vienna in 1529. Under Suleiman the Magnificent it was nearing its height."),
    ("1914", "Ottoman Empire", "Ottoman Empire", 1, "The Balkan Wars of 1912–13 had stripped it of almost all its European lands."),
    ("1914", "Austro-Hungarian Empire", "Austria-Hungary", 1, "A dual monarchy since 1867. The assassination of its heir in Sarajevo set off the First World War."),
    ("1530", "Inca Empire", "Inca Empire", 1, "Tawantinsuyu ran for some 4,000 km along the Andes. Two years later, Pizarro reached Cajamarca."),
    ("1700", "Mughal Empire", "Mughal Empire", 1, "Under Aurangzeb, the Mughals ruled almost the whole subcontinent."),
    ("1700", "Polish–Lithuanian Commonwealth", "Polish–Lithuanian Commonwealth", 1, "One of Europe's largest states, it elected its kings. By 1795 its neighbours had partitioned it out of existence."),
    ("500", "Eastern Roman Empire", "Eastern Roman Empire", 1, "Ruled from Constantinople, it outlived the western empire by nearly a thousand years."),
    ("1279", "Mamluke Sultanate", "Mamluk Sultanate", 2, "Having stopped the Mongols at Ain Jalut in 1260, the Mamluks ruled Egypt and Syria as a single state from Cairo."),
    ("1650", "Safavid Empire", "Safavid Empire", 2, "Shah Abbas had made Isfahan its capital and rebuilt it as one of the great cities of its age."),
    ("1100", "Seljuk Empire", "Great Seljuk Empire", 2, "Its victory at Manzikert in 1071 opened Anatolia to the Turks."),
    ("1100", "Fatimid Caliphate", "Fatimid Caliphate", 2, "This Shi'a caliphate founded Cairo in 969."),
    ("1100", "Kievan Rus", "Kievan Rus'", 2, "Prince Vladimir's baptism in 988 bound the Rus' to Byzantine Christianity."),
    ("1400", "Timurid Empire", "Timurid Empire", 2, "Two years later, Timur crushed the Ottomans at Ankara."),
    ("1279", "Ilkhanate", "Ilkhanate", 2, "Hulagu's heirs ruled Persia after his army sacked Baghdad in 1258."),
    ("1279", "Khanate of the Golden Horde", "Golden Horde", 2, "From Sarai on the Volga, it took tribute from the Russian principalities."),
    ("900", "Abbasid Caliphate", "Abbasid Caliphate", 2, "Its capital, Baghdad, was one of the largest cities on earth."),
    ("700", "Umayyad Caliphate", "Umayyad Caliphate", 2, "Within a dozen years it would reach Spain in the west and the Indus in the east."),
    ("1530", "Mughal Empire", "Mughal Empire", 2, "Babur had founded it four years earlier, after his victory at Panipat."),
    ("500", "Sasanian Empire", "Sasanian Empire", 2, "For four centuries it was Rome's great rival, ruling from Ctesiphon."),
    ("700", "Göktürks", "Göktürk Khaganate", 3, "Its Orkhon inscriptions, carved in the 730s, are the oldest known Turkic texts."),
    ("1492", "Emirate of the White Sheep Turks", "Aq Qoyunlu", 3, "Within a decade the Safavids would take its capital, Tabriz."),
    ("1200", "Kara Khitai Khaganate", "Qara Khitai", 3, "It was founded by Khitans who fled west after their Liao dynasty fell."),
    ("1279", "Mali", "Mali Empire", 3, "Its gold would make Mansa Musa famous in Cairo in 1324."),
]

# Daily challenges: one list of five per day, starting at DAILY_START.
DAILY_START = "2026-10-08"
DAILY = [
    [("1783", "United States of America", "United States", 1, "Britain recognised American independence in the Treaty of Paris this year."),
     ("1100", "Byzantine Empire", "Byzantine Empire", 2, "The First Crusade had marched through Constantinople three years earlier."),
     ("1400", "Sultanate of Delhi", "Delhi Sultanate", 2, "Timur had sacked Delhi just two years earlier."),
     ("700", "Frankish Kingdom", "Frankish Kingdom", 2, "A generation later, Charles Martel stopped an Umayyad army near Tours."),
     ("1880", "Sokoto Caliphate", "Sokoto Caliphate", 3, "Founded by Usman dan Fodio in 1804, it was one of Africa's largest states.")],
    [("1938", "Germany", "Germany", 1, "It annexed Austria in March 1938 and the Sudetenland in October."),
     ("200", "Parthian Empire", "Parthian Empire", 2, "Within three decades it would fall to the Sasanians."),
     ("1279", "Great Khanate", "Yuan Empire", 2, "Kublai Khan completed the conquest of Song China this year."),
     ("900", "Samanid Empire", "Samanid Empire", 3, "From Bukhara, the Samanids sponsored a revival of Persian literature."),
     ("1783", "Viceroyalty of the Río de la Plata", "Viceroyalty of the Río de la Plata", 3, "Created in 1776, it was governed from Buenos Aires.")],
    [("1938", "Empire of Japan", "Empire of Japan", 1, "It had annexed Korea in 1910 and launched a full-scale war on China in 1937."),
     ("1700", "Sweden", "Swedish Empire", 2, "As the Great Northern War began, Sweden ruled much of the Baltic's shores."),
     ("500", "Gupta Empire", "Gupta Empire", 2, "Its era is often called the classical age of India."),
     ("1100", "Almoravid dynasty", "Almoravid Empire", 2, "This Berber dynasty founded Marrakesh and ruled from the Sahara to al-Andalus."),
     ("1279", "Novgorod", "Novgorod Republic", 3, "A merchant republic whose town assembly, the veche, could dismiss its prince.")],
    [("1880", "Egypt", "Egypt", 1, "Two years later, British troops occupied the country."),
     ("1492", "Grand Duchy of Moscow", "Grand Duchy of Moscow", 2, "Ivan III had stopped paying tribute to the Horde in 1480."),
     ("700", "Tufan Empire", "Tibetan Empire", 2, "It fought Tang China for control of the Silk Road oases."),
     ("1815", "Austrian Empire", "Austrian Empire", 2, "Its foreign minister, Metternich, hosted the Congress of Vienna that redrew Europe this year."),
     ("900", "Khazars", "Khazar Khaganate", 3, "Its ruling elite famously converted to Judaism.")],
    [("200", "Han", "Han Empire", 1, "Within twenty years the Han dynasty would break apart into three rival kingdoms."),
     ("1530", "Holy Roman Empire", "Holy Roman Empire", 2, "Its emperor, Charles V, also ruled Spain and its American empire."),
     ("1914", "Abyssinia", "Ethiopia", 2, "It had defeated Italy at Adwa in 1896 and stayed independent."),
     ("1783", "Maratha Confederacy", "Maratha Confederacy", 3, "The Marathas had become the leading power in India as the Mughals declined."),
     ("500", "Axum", "Kingdom of Aksum", 3, "One of the first states to adopt Christianity, in the 4th century.")],
    [("900", "Tang Empire", "Tang Empire", 1, "Seven years later, the Tang dynasty fell."),
     ("1815", "Viceroyalty of New Spain", "New Spain", 2, "Mexico's war of independence had been raging since 1810."),
     ("1914", "Mongolia", "Mongolia", 2, "It had declared independence from the Qing in 1911."),
     ("1880", "Persia", "Qajar Persia", 2, "Earlier in the century, the Qajar shahs had lost their Caucasian lands to Russia."),
     ("bc1", "Xiongnu", "Xiongnu", 3, "This steppe confederation was the Han dynasty's great northern rival.")],
    [("1492", "Ming Empire", "Ming Empire", 1, "Ming treasure fleets had reached East Africa decades before Columbus sailed."),
     ("bc323", "Carthaginian Empire", "Carthage", 2, "A century later, Hannibal would lead its army over the Alps."),
     ("1200", "Song Empire", "Song Empire", 2, "Its capital, Hangzhou, was among the largest cities in the world."),
     ("1650", "Manchu Empire", "Qing Empire", 2, "The Manchu Qing had taken Beijing in 1644."),
     ("1279", "Chagatai Khanate", "Chagatai Khanate", 3, "Named for Genghis Khan's second son, it ruled the heart of Central Asia.")],
]
